const ICONS = {
	list: 'i-lucide-list',
	recipe: 'i-lucide-book',
	planner: 'i-lucide-calendar',
	settings: 'i-lucide-settings',
	plus: 'i-lucide-plus',
	archive: 'i-lucide-archive',
	check: 'i-lucide-check',
	new: 'lucide:sparkles',
	download: 'lucide:download',
	login: 'lucide:log-in',
	trash: 'i-lucide-trash-2',
	leave: 'i-lucide-log-out',
	copy: 'i-lucide-copy',
	search: 'i-lucide-search',
	right: 'i-lucide-chevron-right',
	cloud: 'i-lucide-cloud',
	warn: 'lucide:triangle-alert',
	error: 'lucide:circle-alert',
	blog: 'lucide:newspaper',
	legal: 'i-lucide-scale',
	save: 'i-lucide-save',
	link: 'i-lucide-link',
	listPlus: 'i-lucide-list-plus',
	ellipsis: 'i-lucide-ellipsis-vertical',
	externalLink: 'i-lucide-external-link',
	heart: 'i-lucide-heart',
	bookOpen: 'i-lucide-book-open',
	pencil: 'i-lucide-pencil',
	merge: 'i-lucide-git-merge',
	tags: 'i-lucide-tags',
	users: 'i-lucide-users',
	chartColumn: 'i-lucide-chart-column',
	image: 'i-lucide-image',
	crown: 'i-lucide-crown',
	keyRound: 'i-lucide-key-round',
	house: 'i-lucide-house',
	arrowLeft: 'i-lucide-arrow-left',
	bookX: 'i-lucide-book-x',
	loaderCircle: 'i-lucide-loader-circle',
	badgeCheck: 'lucide:badge-check',
	listChecks: 'i-lucide-list-checks',
	listCheck: 'lucide:list-check',
	refreshCw: 'i-lucide-refresh-cw',
	utensils: 'i-lucide-utensils',
	calendarDays: 'i-lucide-calendar-days',
	home: 'lucide:home',
	info: 'i-lucide-info',
	gripVertical: 'i-lucide-grip-vertical',
	chevronDown: 'i-lucide-chevron-down',
	chevronUp: 'i-lucide-chevron-up',
	smile: 'lucide:smile',
	optionList: 'lucide:list',
	optionListCheck: 'lucide:list-check',
	optionClipboardList: 'lucide:clipboard-list',
	optionShoppingCart: 'lucide:shopping-cart',
	optionShoppingBasket: 'lucide:shopping-basket',
	optionStore: 'lucide:store',
	optionPackage: 'lucide:package',
	optionTag: 'lucide:tag',
	optionBook: 'lucide:book',
	optionBookOpen: 'lucide:book-open',
	optionUtensils: 'lucide:utensils',
	optionChefHat: 'lucide:chef-hat',
	optionApple: 'lucide:apple',
	optionCarrot: 'lucide:carrot',
	optionBeef: 'lucide:beef',
	optionFish: 'lucide:fish',
	optionMilk: 'lucide:milk',
	optionEgg: 'lucide:egg',
	optionWheat: 'lucide:wheat',
	optionCroissant: 'lucide:croissant',
	optionSandwich: 'lucide:sandwich',
	optionPizza: 'lucide:pizza',
	optionSalad: 'lucide:salad',
	optionSoup: 'lucide:soup',
	optionCoffee: 'lucide:coffee',
	optionCloudSun: 'lucide:cloud-sun',
	optionPill: 'lucide:pill'
} as const

type IconKey = keyof typeof ICONS

/**
 * Resolves a shared icon key to its canonical icon name.
 *
 * @param key - Icon key from the shared icon catalog.
 * @returns The configured icon name.
 */
export function getIcon(key: IconKey) {
	return ICONS[key]
}
